version: "3.3"
services:
    nodeserver:
        build:
            context: ./document
        ports:
            - "5000:5000"
    nodeserver1:
        build:
            context: ./pdfBooks
        ports:
            - "5001:5001"
        volumes:
            - /home/guozishu/pdfbooks:/usr/src/wrokspace/pdfs
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "8080:8080"
